on:
  push:
  pull_request:
name: Main workflow
jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: snok/install-poetry@v1.1.3
      - run: poetry install
      - run: poetry run black --check .
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: snok/install-poetry@v1.1.3
      - run: poetry install
      - run: poetry run pytest .
