on:
  schedule:
    # this is UTC time
    - cron: '0 8 * * *'
name: Cron workflow
jobs:
  cron:
    name: send notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - uses: snok/install-poetry@v1.1.4
      - run: poetry install
      - run: poetry run python dianfan.py
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
